############################################
# template setup without poetry
# install: pip install .
# file: pyproject.toml
############################################

[project]
name = "testtools"
requires-python = ">=3.7"
version = "0.0.1"
authors = [
  { name="example", email="example@example.com" },
]
maintainers = [
    { name="example", email="example@example.com" },
]
description = "Run"
readme = "README.md"

dependencies = [
    "boto3~=1.24.67",
    "botocore~=1.27.67",
    "configobj~=5.0.6",
    "cx_oracle",
    "fastparquet==0.8.1",
    "numpy~=1.21.6",
    "openpyxl",
    "oracledb~=1.1.1",
    "pandas==1.3.5",
    "pykeepass==4.0.3",
    "pyspark~=3.3.0",
    "pytest~=7.1.3",
    "setuptools~=65.4.1",
    "sqlalchemy~=1.4.41",
]

# PEP 631 – Dependency specification in pyproject.toml
#[project.optional-dependencies]
#socks = [ 'PySocks >= 1.5.6, != 1.5.7, < 2' ]
#tests = [
#  'coverage>=5.0.3',
#  'pytest',
#  'pytest-benchmark[histogram]>=3.2.1',
#]

#[tool.setuptools]
#py-modules = ['testtools']

[tool.black]
exclude=['tmp', 'dev', 'data', 'volume', 'source', 'transfer', 'notebooks']

[build-system]
requires = ["setuptools>=59.0","setuptools_scm[toml]","wheel"]
build-backend = "setuptools.build_meta"

[project.urls]
homepage = "https://example.com/example/example"
documentation = "https://example.com/example/example"
repository = "https://example.com/example/example"
changelog = "https://example.com/example/example"

[project.scripts]
test_cli = "testtools.cli.entry:vvv"


