############################################
# poetry template setup
# install: poetry install
# file: pyproject.toml
############################################

[tool.poetry]
name = "testtools"
version = "0.0.1"
readme = "README.md"
description = "Run"
authors = ["example <example@example.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<4"
boto3 = "^1.24"
botocore = "^1.27"
configobj = "^5.0"
cx_oracle = "v8.3"
fastparquet = "^0.8"
numpy = "^1.21"
openpyxl = "^3.0"
oracledb = "^1.1"
pandas = "^1.3"
pykeepass = "^4.0"
pyspark = "^3.3"
pytest = "^7.1"
setuptools = "^65.4"
sqlalchemy = "^1.4"

[tool.setuptools]
py-modules = ['testtools']

[tool.black]
exclude=['tmp', 'dev', 'data', 'volume', 'source', 'transfer', 'notebooks']

[build-system]
requires = ["setuptools>=59.0","setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.poetry.urls]
homepage = "https://example.com/example/example"
documentation = "https://example.com/example/example"
repository = "https://example.com/example/example"
changelog = "https://example.com/example/example"

[tool.poetry.scripts]
test_cli = "testtools.cli.entry:vvv"
# my_package_cli = 'my_package.console:run'
# devtest = { callable = "mypackage:test.run_tests", extras = ["test"] }

#[tool.poetry.group.test.dependencies]
#pytest = "*"

#[tool.poetry.group.docs.dependencies]
#mkdocs = "*"
