<?php

/**
 * Created by PhpStorm.
 * User: emil
 * Date: 07.09.16
 * Time: 14:05
 */

function getISORegionSAP()
{

	$arRegions = array(

		array("500", "AR", "00", "", "", "Capital Federal", "Argentinien", "Argentina"),
		array("500", "AR", "01", "", "", "Buenos Aires", "Argentinien", "Argentina"),
		array("500", "AR", "02", "", "", "Catamarca", "Argentinien", "Argentina"),
		array("500", "AR", "03", "", "", "Córdoba", "Argentinien", "Argentina"),
		array("500", "AR", "04", "", "", "Corrientes", "Argentinien", "Argentina"),
		array("500", "AR", "05", "", "", "Entre Rios", "Argentinien", "Argentina"),
		array("500", "AR", "06", "", "", "Jujuy", "Argentinien", "Argentina"),
		array("500", "AR", "07", "", "", "Mendoza", "Argentinien", "Argentina"),
		array("500", "AR", "08", "", "", "La Rioja", "Argentinien", "Argentina"),
		array("500", "AR", "09", "", "", "Salta", "Argentinien", "Argentina"),
		array("500", "AR", "10", "", "", "San Juan", "Argentinien", "Argentina"),
		array("500", "AR", "11", "", "", "San Luis", "Argentinien", "Argentina"),
		array("500", "AR", "12", "", "", "Santa Fé", "Argentinien", "Argentina"),
		array("500", "AR", "13", "", "", "Santiago del Estero", "Argentinien", "Argentina"),
		array("500", "AR", "14", "", "", "Tucumán", "Argentinien", "Argentina"),
		array("500", "AR", "16", "", "", "Chaco", "Argentinien", "Argentina"),
		array("500", "AR", "17", "", "", "Chubut", "Argentinien", "Argentina"),
		array("500", "AR", "18", "", "", "Formosa", "Argentinien", "Argentina"),
		array("500", "AR", "19", "", "", "Misiones", "Argentinien", "Argentina"),
		array("500", "AR", "20", "", "", "Neuquen", "Argentinien", "Argentina"),
		array("500", "AR", "21", "", "", "La Pampa", "Argentinien", "Argentina"),
		array("500", "AR", "22", "", "", "Rio Negro", "Argentinien", "Argentina"),
		array("500", "AR", "23", "", "", "Santa Cruz", "Argentinien", "Argentina"),
		array("500", "AR", "24", "", "", "Tierra de Fuego", "Argentinien", "Argentina"),
		array("500", "AR", "99", "", "", "außerhalb", "Argentinien", "Argentina"),

		array("500", "AT", "99", "", "", "außerhalb", "Österreich", "Austria"),
		array("500", "AT", "B ", "", "", "Burgenland", "Österreich", "Austria"),
		array("500", "AT", "K ", "", "", "Kärnten", "Österreich", "Austria"),
		array("500", "AT", "NÖ", "", "", "Niederösterreich", "Österreich", "Austria"),
		array("500", "AT", "OÖ", "", "", "Oberösterreich", "Österreich", "Austria"),
		array("500", "AT", "S ", "", "", "Salzburg", "Österreich", "Austria"),
		array("500", "AT", "ST", "", "", "Steiermark", "Österreich", "Austria"),
		array("500", "AT", "T ", "", "", "Tirol", "Österreich", "Austria"),
		array("500", "AT", "V ", "", "", "Vorarlberg", "Österreich", "Austria"),
		array("500", "AT", "W ", "", "", "Wien", "Österreich", "Austria"),

		array("500", "AU", "99", "", "", "außerhalb", "Australien", "Australia"),
		array("500", "AU", "ACT", "", "", "Aust Capital Terr", "Australien", "Australia"),
		array("500", "AU", "NSW", "", "", "New South Wales", "Australien", "Australia"),
		array("500", "AU", "NT", "NT", "", "Northern Territory", "Australien", "Australia"),
		array("500", "AU", "QLD", "", "", "Queensland", "Australien", "Australia"),
		array("500", "AU", "SA", "SA", "", "South Australia", "Australien", "Australia"),
		array("500", "AU", "TAS", "", "", "Tasmania", "Australien", "Australia"),
		array("500", "AU", "VIC", "", "", "Victoria", "Australien", "Australia"),
		array("500", "AU", "WA", "WA", "", "West Australia", "Australien", "Australia"),

		array("500", "BE", "BE", "", "", "Belgien", "Belgien", "Belgium"),

		array("500", "BR", "99", "", "", "außerhalb", "Brasilien", "Brazil"),
		array("500", "BR", "AC", "", "", "Acre", "Brasilien", "Brazil"),
		array("500", "BR", "AL", "", "", "Alagoas", "Brasilien", "Brazil"),
		array("500", "BR", "AM", "", "", "Amazonas", "Brasilien", "Brazil"),
		array("500", "BR", "AP", "", "", "Amapá", "Brasilien", "Brazil"),
		array("500", "BR", "BA", "", "", "Bahia", "Brasilien", "Brazil"),
		array("500", "BR", "CE", "", "", "Ceará", "Brasilien", "Brazil"),
		array("500", "BR", "DF", "", "", "Brasília", "Brasilien", "Brazil"),
		array("500", "BR", "ES", "", "", "Espírito San", "Brasilien", "Brazil"),
		array("500", "BR", "GO", "", "", "Goiás", "Brasilien", "Brazil"),
		array("500", "BR", "MA", "", "", "Maranhão", "Brasilien", "Brazil"),
		array("500", "BR", "MG", "", "", "Minas Gerais", "Brasilien", "Brazil"),
		array("500", "BR", "MS", "", "", "Mato Grosso", "Brasilien", "Brazil"),
		array("500", "BR", "MT", "", "", "Mato Grosso", "Brasilien", "Brazil"),
		array("500", "BR", "PA", "", "", "Para", "Brasilien", "Brazil"),
		array("500", "BR", "PB", "", "", "Paraíba", "Brasilien", "Brazil"),
		array("500", "BR", "PE", "", "", "Pernambuco", "Brasilien", "Brazil"),
		array("500", "BR", "PI", "", "", "Piauí", "Brasilien", "Brazil"),
		array("500", "BR", "PR", "", "", "Paraná", "Brasilien", "Brazil"),
		array("500", "BR", "RJ", "", "", "Rio de Janeiro", "Brasilien", "Brazil"),
		array("500", "BR", "RN", "", "", "Rio Grande do Nort", "Brasilien", "Brazil"),
		array("500", "BR", "RO", "", "", "Rondônia", "Brasilien", "Brazil"),
		array("500", "BR", "RR", "", "", "Roraima", "Brasilien", "Brazil"),
		array("500", "BR", "RS", "", "", "Rio Grande do Sul", "Brasilien", "Brazil"),
		array("500", "BR", "SC", "", "", "Santa Catarina", "Brasilien", "Brazil"),
		array("500", "BR", "SE", "", "", "Sergipe", "Brasilien", "Brazil"),
		array("500", "BR", "SP", "", "", "São Paulo", "Brasilien", "Brazil"),
		array("500", "BR", "TO", "", "", "Tocantins", "Brasilien", "Brazil"),

		array("500", "CA", "99", "", "", "außerhalb", "Kanada", "Canada"),
		array("500", "CA", "AB", "AB", "", "Alberta", "Kanada", "Canada"),
		array("500", "CA", "BC", "BC", "", "British Columbia", "Kanada", "Canada"),
		array("500", "CA", "MB", "MB", "", "Manitoba", "Kanada", "Canada"),
		array("500", "CA", "NB", "NB", "", "New Brunswick", "Kanada", "Canada"),
		array("500", "CA", "NF", "NF", "", "New Foundland", "Kanada", "Canada"),
		array("500", "CA", "NS", "NS", "", "Nova Scotia", "Kanada", "Canada"),
		array("500", "CA", "NT", "NT", "", " ", "Kanada", "Canada"),
		array("500", "CA", "ON", "ON", "", "Ontario", "Kanada", "Canada"),
		array("500", "CA", "PE", "PE", "", " ", "Kanada", "Canada"),
		array("500", "CA", "QC", "QC", "", " ", "Kanada", "Canada"),
		array("500", "CA", "SK", "SK", "", " ", "Kanada", "Canada"),
		array("500", "CA", "YT", "YT", "", " ", "Kanada", "Canada"),
		array("500", "CA", "ZZ", "ZZ", "", " ", "Kanada", "Canada"),

		array("500", "CH", "99", "", "", "außerhalb", "Schweiz", "Switzerland"),
		array("500", "CH", "AG", "", "", "Aargau", "Schweiz", "Switzerland"),
		array("500", "CH", "AI", "", "", "Appenzell Innerrh.", "Schweiz", "Switzerland"),
		array("500", "CH", "AR", "", "", "Appenzell Ausserrh.", "Schweiz", "Switzerland"),
		array("500", "CH", "BE", "", "", "Bern", "Schweiz", "Switzerland"),
		array("500", "CH", "BL", "", "", "Basel Land", "Schweiz", "Switzerland"),
		array("500", "CH", "BS", "", "", "Basel Stadt", "Schweiz", "Switzerland"),
		array("500", "CH", "FR", "", "", "Fribourg", "Schweiz", "Switzerland"),
		array("500", "CH", "GE", "", "", "Geneve", "Schweiz", "Switzerland"),
		array("500", "CH", "GL", "", "", "Glarus", "Schweiz", "Switzerland"),
		array("500", "CH", "GR", "", "", "Graubünden", "Schweiz", "Switzerland"),
		array("500", "CH", "JU", "", "", "Jura", "Schweiz", "Switzerland"),
		array("500", "CH", "LU", "", "", "Luzern", "Schweiz", "Switzerland"),
		array("500", "CH", "NE", "", "", "Neuchatel", "Schweiz", "Switzerland"),
		array("500", "CH", "NW", "", "", "Nidwalden", "Schweiz", "Switzerland"),
		array("500", "CH", "OW", "", "", "Obwalden", "Schweiz", "Switzerland"),
		array("500", "CH", "SG", "", "", "St. Gallen", "Schweiz", "Switzerland"),
		array("500", "CH", "SH", "", "", "Schaffhausen", "Schweiz", "Switzerland"),
		array("500", "CH", "SO", "", "", "Solothurn", "Schweiz", "Switzerland"),
		array("500", "CH", "SZ", "", "", "Schwyz", "Schweiz", "Switzerland"),
		array("500", "CH", "TG", "", "", "Thurgau", "Schweiz", "Switzerland"),
		array("500", "CH", "TI", "", "", "Ticino", "Schweiz", "Switzerland"),
		array("500", "CH", "UR", "", "", "Uri", "Schweiz", "Switzerland"),
		array("500", "CH", "VD", "", "", "Vaud", "Schweiz", "Switzerland"),
		array("500", "CH", "VS", "", "", "Valais", "Schweiz", "Switzerland"),
		array("500", "CH", "ZG", "", "", "Zug", "Schweiz", "Switzerland"),
		array("500", "CH", "ZH", "", "", "Zürich", "Schweiz", "Switzerland"),

		array("500", "CN", "010", "", "", "Beijing", "China", "China"),
		array("500", "CN", "020", "", "", "Shanghai", "China", "China"),
		array("500", "CN", "030", "", "", "Tianjin", "China", "China"),
		array("500", "CN", "040", "", "", "Nei Mongol", "China", "China"),
		array("500", "CN", "050", "", "", "Shanxi", "China", "China"),
		array("500", "CN", "060", "", "", "Hebei", "China", "China"),
		array("500", "CN", "070", "", "", "Liaoning", "China", "China"),
		array("500", "CN", "080", "", "", "Jilin", "China", "China"),
		array("500", "CN", "090", "", "", "Heilongjiang", "China", "China"),
		array("500", "CN", "100", "", "", "Jiangsu", "China", "China"),
		array("500", "CN", "110", "", "", "Anhui", "China", "China"),
		array("500", "CN", "120", "", "", "Shandong", "China", "China"),
		array("500", "CN", "130", "", "", "Zhejiang", "China", "China"),
		array("500", "CN", "140", "", "", "Jiangxi", "China", "China"),
		array("500", "CN", "150", "", "", "Fujian", "China", "China"),
		array("500", "CN", "160", "", "", "Hunan", "China", "China"),
		array("500", "CN", "170", "", "", "Hubei", "China", "China"),
		array("500", "CN", "180", "", "", "Henan", "China", "China"),
		array("500", "CN", "190", "", "", "Guangdong", "China", "China"),
		array("500", "CN", "200", "", "", "Hainan", "China", "China"),
		array("500", "CN", "210", "", "", "Guangxi", "China", "China"),
		array("500", "CN", "220", "", "", "Guizhou", "China", "China"),
		array("500", "CN", "230", "", "", "Sichuan", "China", "China"),
		array("500", "CN", "240", "", "", "Yunnan", "China", "China"),
		array("500", "CN", "250", "", "", "Shaanxi", "China", "China"),
		array("500", "CN", "260", "", "", "Gansu", "China", "China"),
		array("500", "CN", "270", "", "", "Ningxia", "China", "China"),
		array("500", "CN", "280", "", "", "Qinghai", "China", "China"),
		array("500", "CN", "290", "", "", "Xinjiang ", "China", "China"),
		array("500", "CN", "300", "", "", "Xizang", "China", "China"),
		array("500", "CN", "310", "", "", "Taiwan", "China", "China"),
		array("500", "CN", "99", "", "", "außerhalb", "China", "China"),

		array("500", "CZ", "1 ", "", "", "Allgemein", "Tschechische Republik", "Czech Republic"),
		array("500", "CZ", "99", "", "", "außerhalb", "Tschechische Republik", "Czech Republic"),

		array("500", "DE", "01", "", "01", "Schleswig-Holstein", "Deutschland", "Germany"),
		array("500", "DE", "02", "", "02", "Hamburg", "Deutschland", "Germany"),
		array("500", "DE", "03", "", "03", "Niedersachsen", "Deutschland", "Germany"),
		array("500", "DE", "04", "", "04", "Bremen", "Deutschland", "Germany"),
		array("500", "DE", "05", "", "05", "Nordrhein-Westfalen", "Deutschland", "Germany"),
		array("500", "DE", "06", "", "06", "Hessen", "Deutschland", "Germany"),
		array("500", "DE", "07", "", "07", "Rheinland-Pfalz", "Deutschland", "Germany"),
		array("500", "DE", "08", "", "08", "Baden-Württemberg", "Deutschland", "Germany"),
		array("500", "DE", "09", "", "09", "Bayern", "Deutschland", "Germany"),
		array("500", "DE", "10", "", "10", "Saarland", "Deutschland", "Germany"),
		array("500", "DE", "11", "", "11", "Berlin", "Deutschland", "Germany"),
		array("500", "DE", "12", "", "12", "Brandenburg", "Deutschland", "Germany"),
		array("500", "DE", "13", "", "13", "Mecklenburg-Vorpomm.", "Deutschland", "Germany"),
		array("500", "DE", "14", "", "14", "Sachsen", "Deutschland", "Germany"),
		array("500", "DE", "15", "", "15", "Sachsen-Anhalt", "Deutschland", "Germany"),
		array("500", "DE", "16", "", "16", "Thüringen", "Deutschland", "Germany"),
		array("500", "DE", "99", "", "", "außerhalb", "Deutschland", "Germany"),

		array("500", "DK", "001", "", "", "Staden København", "Dänemark", "Denmark"),
		array("500", "DK", "002", "", "", "Århus", "Dänemark", "Denmark"),
		array("500", "DK", "003", "", "", "Bornholm", "Dänemark", "Denmark"),
		array("500", "DK", "004", "", "", "Frederiksborg", "Dänemark", "Denmark"),
		array("500", "DK", "005", "", "", "Fyn", "Dänemark", "Denmark"),
		array("500", "DK", "006", "", "", "København", "Dänemark", "Denmark"),
		array("500", "DK", "007", "", "", "Nordjylland", "Dänemark", "Denmark"),
		array("500", "DK", "008", "", "", "Ribe", "Dänemark", "Denmark"),
		array("500", "DK", "009", "", "", "Ringkøbing", "Dänemark", "Denmark"),
		array("500", "DK", "010", "", "", "Roskilde", "Dänemark", "Denmark"),
		array("500", "DK", "011", "", "", "Sønderjyland", "Dänemark", "Denmark"),
		array("500", "DK", "012", "", "", "Storstrøm", "Dänemark", "Denmark"),
		array("500", "DK", "013", "", "", "Vejle", "Dänemark", "Denmark"),
		array("500", "DK", "014", "", "", "Vestsjaelland", "Dänemark", "Denmark"),
		array("500", "DK", "015", "", "", "Viborg", "Dänemark", "Denmark"),
		array("500", "DK", "99", "", "", "außerhalb", "Dänemark", "Denmark"),

		array("500", "ES", "01", "", "", "Alava", "Spanien", "Spain"),
		array("500", "ES", "02", "", "", "Albacete", "Spanien", "Spain"),
		array("500", "ES", "03", "", "", "Alicante", "Spanien", "Spain"),
		array("500", "ES", "04", "", "", "Almería", "Spanien", "Spain"),
		array("500", "ES", "05", "", "", "Avila", "Spanien", "Spain"),
		array("500", "ES", "06", "", "", "Badajoz", "Spanien", "Spain"),
		array("500", "ES", "07", "", "", "Baleares", "Spanien", "Spain"),
		array("500", "ES", "08", "", "", "Barcelona", "Spanien", "Spain"),
		array("500", "ES", "09", "", "", "Burgos", "Spanien", "Spain"),
		array("500", "ES", "10", "", "", "Cáceres", "Spanien", "Spain"),
		array("500", "ES", "11", "", "", "Cadiz", "Spanien", "Spain"),
		array("500", "ES", "12", "", "", "Castellón", "Spanien", "Spain"),
		array("500", "ES", "13", "", "", "Ciudad Real", "Spanien", "Spain"),
		array("500", "ES", "14", "", "", "Córdoba", "Spanien", "Spain"),
		array("500", "ES", "15", "", "", "La Coruña", "Spanien", "Spain"),
		array("500", "ES", "16", "", "", "Cuenca", "Spanien", "Spain"),
		array("500", "ES", "17", "", "", "Gerona", "Spanien", "Spain"),
		array("500", "ES", "18", "", "", "Granada", "Spanien", "Spain"),
		array("500", "ES", "19", "", "", "Guadalajara", "Spanien", "Spain"),
		array("500", "ES", "20", "", "", "Guipúzcoa", "Spanien", "Spain"),
		array("500", "ES", "21", "", "", "Huelva", "Spanien", "Spain"),
		array("500", "ES", "22", "", "", "Huesca", "Spanien", "Spain"),
		array("500", "ES", "23", "", "", "Jaén", "Spanien", "Spain"),
		array("500", "ES", "24", "", "", "León", "Spanien", "Spain"),
		array("500", "ES", "25", "", "", "Lérida", "Spanien", "Spain"),
		array("500", "ES", "26", "", "", "La Rioja", "Spanien", "Spain"),
		array("500", "ES", "27", "", "", "Lugo", "Spanien", "Spain"),
		array("500", "ES", "28", "", "", "Madrid", "Spanien", "Spain"),
		array("500", "ES", "29", "", "", "Málaga", "Spanien", "Spain"),
		array("500", "ES", "30", "", "", "Murcia", "Spanien", "Spain"),
		array("500", "ES", "31", "", "", "Navarra", "Spanien", "Spain"),
		array("500", "ES", "32", "", "", "Orense", "Spanien", "Spain"),
		array("500", "ES", "33", "", "", "Asturias", "Spanien", "Spain"),
		array("500", "ES", "34", "", "", "Palencia", "Spanien", "Spain"),
		array("500", "ES", "35", "", "", "Las Palmas", "Spanien", "Spain"),
		array("500", "ES", "36", "", "", "Pontevedra", "Spanien", "Spain"),
		array("500", "ES", "37", "", "", "Salamanca", "Spanien", "Spain"),
		array("500", "ES", "38", "", "", "Sta. Cruz Tenerife", "Spanien", "Spain"),
		array("500", "ES", "39", "", "", "Cantabria", "Spanien", "Spain"),
		array("500", "ES", "40", "", "", "Segovia", "Spanien", "Spain"),
		array("500", "ES", "41", "", "", "Sevilla", "Spanien", "Spain"),
		array("500", "ES", "42", "", "", "Soria", "Spanien", "Spain"),
		array("500", "ES", "43", "", "", "Tarragona", "Spanien", "Spain"),
		array("500", "ES", "44", "", "", "Teruel", "Spanien", "Spain"),
		array("500", "ES", "45", "", "", "Toledo", "Spanien", "Spain"),
		array("500", "ES", "46", "", "", "Valencia", "Spanien", "Spain"),
		array("500", "ES", "47", "", "", "Valladolid", "Spanien", "Spain"),
		array("500", "ES", "48", "", "", "Vizcaya", "Spanien", "Spain"),
		array("500", "ES", "49", "", "", "Zamora", "Spanien", "Spain"),
		array("500", "ES", "50", "", "", "Zaragoza", "Spanien", "Spain"),
		array("500", "ES", "99", "", "", "außerhalb", "Spanien", "Spain"),

		array("500", "FI", "001", "", "", "Ahvenanmaa", "Finnland", "Finland"),
		array("500", "FI", "002", "", "", "Häme", "Finnland", "Finland"),
		array("500", "FI", "003", "", "", "Keski-Suomi", "Finnland", "Finland"),
		array("500", "FI", "004", "", "", "Kuopio", "Finnland", "Finland"),
		array("500", "FI", "005", "", "", "Kymi", "Finnland", "Finland"),
		array("500", "FI", "006", "", "", "Lappi", "Finnland", "Finland"),
		array("500", "FI", "007", "", "", "Mikkeli", "Finnland", "Finland"),
		array("500", "FI", "008", "", "", "Oulu", "Finnland", "Finland"),
		array("500", "FI", "009", "", "", "Pohjois-Karjala", "Finnland", "Finland"),
		array("500", "FI", "010", "", "", "Turku ja Pori", "Finnland", "Finland"),
		array("500", "FI", "011", "", "", "Uusimaa", "Finnland", "Finland"),
		array("500", "FI", "012", "", "", "Vaasa", "Finnland", "Finland"),
		array("500", "FI", "99", "", "", "außerhalb", "Finnland", "Finland"),

		array("500", "FR", "01", "", "", "Ain", "Frankreich", "France"),
		array("500", "FR", "02", "", "", "Aisne", "Frankreich", "France"),
		array("500", "FR", "03", "", "", "Allier", "Frankreich", "France"),
		array("500", "FR", "04", "", "", "Alpes (Hte-Provence)", "Frankreich", "France"),
		array("500", "FR", "05", "", "", "Alpes (Hautes)", "Frankreich", "France"),
		array("500", "FR", "06", "", "", "Alpes-Maritimes", "Frankreich", "France"),
		array("500", "FR", "07", "", "", "Ardèche", "Frankreich", "France"),
		array("500", "FR", "08", "", "", "Ardennes", "Frankreich", "France"),
		array("500", "FR", "09", "", "", "Ariège", "Frankreich", "France"),
		array("500", "FR", "10", "", "", "Aube", "Frankreich", "France"),
		array("500", "FR", "11", "", "", "Aude", "Frankreich", "France"),
		array("500", "FR", "12", "", "", "Aveyron", "Frankreich", "France"),
		array("500", "FR", "13", "", "", "Bouches-du-Rhône", "Frankreich", "France"),
		array("500", "FR", "14", "", "", "Calvados", "Frankreich", "France"),
		array("500", "FR", "15", "", "", "Cantal", "Frankreich", "France"),
		array("500", "FR", "16", "", "", "Charente", "Frankreich", "France"),
		array("500", "FR", "17", "", "", "Charente-Maritime", "Frankreich", "France"),
		array("500", "FR", "18", "", "", "Cher", "Frankreich", "France"),
		array("500", "FR", "19", "", "", "Corrèze", "Frankreich", "France"),
		array("500", "FR", "21", "", "", "Côte-d'Or", "Frankreich", "France"),
		array("500", "FR", "22", "", "", "Côtes-d'Armor", "Frankreich", "France"),
		array("500", "FR", "23", "", "", "Creuse", "Frankreich", "France"),
		array("500", "FR", "24", "", "", "Dordogne", "Frankreich", "France"),
		array("500", "FR", "25", "", "", "Doubs", "Frankreich", "France"),
		array("500", "FR", "26", "", "", "Drôme", "Frankreich", "France"),
		array("500", "FR", "27", "", "", "Eure", "Frankreich", "France"),
		array("500", "FR", "28", "", "", "Eure-et-Loir", "Frankreich", "France"),
		array("500", "FR", "29", "", "", "Finistère", "Frankreich", "France"),
		array("500", "FR", "2A", "", "", "Corse-du-Sud", "Frankreich", "France"),
		array("500", "FR", "2B", "", "", "Corse-du-Nord", "Frankreich", "France"),
		array("500", "FR", "30", "", "", "Gard", "Frankreich", "France"),
		array("500", "FR", "31", "", "", "Garonne (Haute)", "Frankreich", "France"),
		array("500", "FR", "32", "", "", "Gers", "Frankreich", "France"),
		array("500", "FR", "33", "", "", "Gironde", "Frankreich", "France"),
		array("500", "FR", "34", "", "", "Hérault", "Frankreich", "France"),
		array("500", "FR", "35", "", "", "Ille-et-Vilaine", "Frankreich", "France"),
		array("500", "FR", "36", "", "", "Indre", "Frankreich", "France"),
		array("500", "FR", "37", "", "", "Indre-et-Loire", "Frankreich", "France"),
		array("500", "FR", "38", "", "", "Isère", "Frankreich", "France"),
		array("500", "FR", "39", "", "", "Jura", "Frankreich", "France"),
		array("500", "FR", "40", "", "", "Landes", "Frankreich", "France"),
		array("500", "FR", "41", "", "", "Loir-et-Cher", "Frankreich", "France"),
		array("500", "FR", "42", "", "", "Loire", "Frankreich", "France"),
		array("500", "FR", "43", "", "", "Loire (Haute)", "Frankreich", "France"),
		array("500", "FR", "44", "", "", "Loire-Atlantique", "Frankreich", "France"),
		array("500", "FR", "45", "", "", "Loiret", "Frankreich", "France"),
		array("500", "FR", "46", "", "", "Lot", "Frankreich", "France"),
		array("500", "FR", "47", "", "", "Lot-et-Garonne", "Frankreich", "France"),
		array("500", "FR", "48", "", "", "Lozère", "Frankreich", "France"),
		array("500", "FR", "49", "", "", "Maine-et-Loire", "Frankreich", "France"),
		array("500", "FR", "50", "", "", "Manche", "Frankreich", "France"),
		array("500", "FR", "51", "", "", "Marne", "Frankreich", "France"),
		array("500", "FR", "52", "", "", "Marne (Haute)", "Frankreich", "France"),
		array("500", "FR", "53", "", "", "Mayenne", "Frankreich", "France"),
		array("500", "FR", "54", "", "", "Meurthe-et-Moselle", "Frankreich", "France"),
		array("500", "FR", "55", "", "", "Meuse", "Frankreich", "France"),
		array("500", "FR", "56", "", "", "Morbihan", "Frankreich", "France"),
		array("500", "FR", "57", "", "", "Moselle", "Frankreich", "France"),
		array("500", "FR", "58", "", "", "Nièvre", "Frankreich", "France"),
		array("500", "FR", "59", "", "", "Nord", "Frankreich", "France"),
		array("500", "FR", "60", "", "", "Oise", "Frankreich", "France"),
		array("500", "FR", "61", "", "", "Orne", "Frankreich", "France"),
		array("500", "FR", "62", "", "", "Pas-de-Calais", "Frankreich", "France"),
		array("500", "FR", "63", "", "", "Puy-de-Dôme", "Frankreich", "France"),
		array("500", "FR", "64", "", "", "Pyrénées-Atlantiques", "Frankreich", "France"),
		array("500", "FR", "65", "", "", "Pyrénées (Hautes)", "Frankreich", "France"),
		array("500", "FR", "66", "", "", "Pyrénées-Orientales", "Frankreich", "France"),
		array("500", "FR", "67", "", "", "Rhin (Bas)", "Frankreich", "France"),
		array("500", "FR", "68", "", "", "Rhin (Haut)", "Frankreich", "France"),
		array("500", "FR", "69", "", "", "Rhône", "Frankreich", "France"),
		array("500", "FR", "70", "", "", "Saône (Haute)", "Frankreich", "France"),
		array("500", "FR", "71", "", "", "Saône-et-Loire", "Frankreich", "France"),
		array("500", "FR", "72", "", "", "Sarthe", "Frankreich", "France"),
		array("500", "FR", "73", "", "", "Savoie", "Frankreich", "France"),
		array("500", "FR", "74", "", "", "Savoie (Haute)", "Frankreich", "France"),
		array("500", "FR", "75", "", "", "Paris", "Frankreich", "France"),
		array("500", "FR", "76", "", "", "Seine-Maritime", "Frankreich", "France"),
		array("500", "FR", "77", "", "", "Seine-et-Marne", "Frankreich", "France"),
		array("500", "FR", "78", "", "", "Yvelines", "Frankreich", "France"),
		array("500", "FR", "79", "", "", "Sèvres (Deux)", "Frankreich", "France"),
		array("500", "FR", "80", "", "", "Somme", "Frankreich", "France"),
		array("500", "FR", "81", "", "", "Tarn", "Frankreich", "France"),
		array("500", "FR", "82", "", "", "Tarn-et-Garonne", "Frankreich", "France"),
		array("500", "FR", "83", "", "", "Var", "Frankreich", "France"),
		array("500", "FR", "84", "", "", "Vaucluse", "Frankreich", "France"),
		array("500", "FR", "85", "", "", "Vendée", "Frankreich", "France"),
		array("500", "FR", "86", "", "", "Vienne", "Frankreich", "France"),
		array("500", "FR", "87", "", "", "Vienne (Haute)", "Frankreich", "France"),
		array("500", "FR", "88", "", "", "Vosges", "Frankreich", "France"),
		array("500", "FR", "89", "", "", "Yonne", "Frankreich", "France"),
		array("500", "FR", "90", "", "", "Territ.-de-Belfort", "Frankreich", "France"),
		array("500", "FR", "91", "", "", "Essonne", "Frankreich", "France"),
		array("500", "FR", "92", "", "", "Hauts-de-Seine", "Frankreich", "France"),
		array("500", "FR", "93", "", "", "Seine-Saint-Denis", "Frankreich", "France"),
		array("500", "FR", "94", "", "", "Val-de-Marne", "Frankreich", "France"),
		array("500", "FR", "95", "", "", "Val-d'Oise", "Frankreich", "France"),
		array("500", "FR", "97", "", "", "D.O.M.-T.O.M.", "Frankreich", "France"),
		array("500", "FR", "971", "", "", "Guadeloupe", "Frankreich", "France"),
		array("500", "FR", "972", "", "", "Martinique", "Frankreich", "France"),
		array("500", "FR", "973", "", "", "Guyane", "Frankreich", "France"),
		array("500", "FR", "974", "", "", "Réunion", "Frankreich", "France"),
		array("500", "FR", "975", "", "", "Saint-Pierre-et-Miq.", "Frankreich", "France"),
		array("500", "FR", "976", "", "", "Wallis-et-Futuna", "Frankreich", "France"),
		array("500", "FR", "98", "", "", "Tahiti", "Frankreich", "France"),
		array("500", "FR", "99", "", "", "außerhalb", "Frankreich", "France"),

		array("500", "GB", "99", "", "", "außerhalb", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ABD", "", "", "Aberdeenshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "AGY", "", "", "Anglesey", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ALD", "", "", "Alderney", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "AM", "", "", "Armagh", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ANS", "", "", "Angus", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "AR", "", "", "Ards", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ARL", "", "", "Argyllshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "AT", "", "", "Antrim", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "AVN", "", "", "Avon", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "AYR", "", "", "Ayrshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BA", "", "", "Ballymena", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BAN", "", "", "Banffshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BB", "", "", "Blackburn", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BE", "", "", "Bedfordshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BEW", "", "", "Berwickshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BF", "", "", "Bracknell Forest", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BH", "", "", "Brighton & Hove", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BK", "", "", "Berkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BL", "", "", "Belfast", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BM", "", "", "Bournemouth", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BN", "", "", "Banbridge", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BO", "", "", "Borders", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BP", "", "", "Blackpool", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BR", "", "", "Bristol", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BRE", "", "", "Breconshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BS", "", "", "Bath&NthEstSomerset", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BU", "", "", "Buckinghamshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BUT", "", "", "Bute", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "BY", "", "", "Ballymoney", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CA", "", "", "Cambridgeshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CAE", "", "", "Caernarvonshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CAI", "", "", "Caithness", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CE", "", "", "Central", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CG", "", "", "Craigavon", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CGN", "", "", "Cardiganshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CH", "", "", "Cheshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CI", "", "", "Coleraine", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CK", "", "", "Cookstown", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CL", "", "", "Clwyd", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CLK", "", "", "Clackmannanshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CMN", "", "", "Carmarthenshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CO", "", "", "Cornwall", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CR", "", "", "Carrickfergus", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CS", "", "", "Castlereagh", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CU", "", "", "Cumbria", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CUL", "", "", "Cumberland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "CV", "", "", "Cleveland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DB", "", "", "Derbyshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DEN", "", "", "Denbighshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DF", "", "", "Dumfries a. Galloway", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DFS", "", "", "Dumfries-shire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DG", "", "", "Dungannon", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DL", "", "", "Darlington", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DN", "", "", "Down", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DNB", "", "", "Dunbartonshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DO", "", "", "Dorset", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DU", "", "", "Durham", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DV", "", "", "Devon", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "DY", "", "", "Dyfed", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ELN", "", "", "East Lothian", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ER", "", "", "East RidingYorkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ES", "", "", "Essex", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "FI", "", "", "Fife", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "FLN", "", "", "Flintshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "FM", "", "", "Fermanagh", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GL", "", "", "Gloucestershire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GLA", "", "", "Glamorgan", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GM", "", "", "Greater Manchester", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GR", "", "", "Grampian", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GS", "", "", "Sth. Gloucestershire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GSY", "", "", "Guernsey", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GW", "", "", "Gwent", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "GY", "", "", "Gwynedd", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HA", "", "", "Hampshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HEF", "", "", "Herefordshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HI", "", "", "Highland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HL", "", "", "Halton", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HR", "", "", "Hartlepool", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HT", "", "", "Hertfordshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HUM", "", "", "Humberside", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HUN", "", "", "Huntingdonshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "HW", "", "", "Herefd. and Worcest.", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "INV", "", "", "Inverness-shire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "IW", "", "", "Isle of Wight", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "JSY", "", "", "Jersey", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "KCD", "", "", "Kincardineshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "KE", "", "", "Kent", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "KH", "", "", "Kingston-upon-Hull", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "KKD", "", "", "Kirkcudbrightshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "KRS", "", "", "Kinross-shire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LA", "", "", "Lancashire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LC", "", "", "Leicester City", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LD", "", "", "Londonderry", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LE", "", "", "Leicestershire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LI", "", "", "Lincolnshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LKS", "", "", "Lanarkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LM", "", "", "Limavady", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LO", "", "", "Greater London", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LR", "", "", "Larne", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LS", "", "", "Lisburn", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LT", "", "", "Lothian", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "LU", "", "", "Luton", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MA", "", "", "Magherafelt", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MER", "", "", "Merionethshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MG", "", "", "Mid Glamorgan", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MGY", "", "", "Montgomeryshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MI", "", "", "Middlesborough", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MK", "", "", "Milton Keynes", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MLN", "", "", "Midlothian", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MO", "", "", "Moyle", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MON", "", "", "Monmouthshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MOR", "", "", "Morayshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "MY", "", "", "Merseyside", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NA", "", "", "Newtownabbey", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NAI", "", "", "Nairn", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NB", "", "", "Newbury", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NC", "", "", "Nottingham City", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ND", "", "", "North Down", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NE", "", "", "NthEast Lincolnshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NH", "", "", "Northamptonshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NK", "", "", "Norfolk", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NL", "", "", "North Lincolnshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NM", "", "", "Newry and Mourne", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NRY", "", "", "North Riding of York", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NS", "", "", "North Somerset", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NT", "", "", "Nottinghamshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "NU", "", "", "Northumberland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "OM", "", "", "Omagh", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "OR", "", "", "Orkney", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "OX", "", "", "Oxfordshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PB", "", "", "Peterborough", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PEE", "", "", "Peebles-shire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PEM", "", "", "Pembrokeshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PER", "", "", "Perth", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PL", "", "", "Poole", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PM", "", "", "Portsmouth", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PO", "", "", "Powys", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "PY", "", "", "Plymouth", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "RAD", "", "", "Radnorshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "RD", "", "", "Redcar and Cleveland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "RE", "", "", "Reading", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "RFW", "", "", "Renfrewshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "RM", "", "", "Rochester up. Medway", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ROC", "", "", "Ross and Cromarty", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ROX", "", "", "Roxburghshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "RU", "", "", "Rutland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SC", "", "", "Strathclyde", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SD", "", "", "Southend", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SE", "", "", "East Sussex", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SG", "", "", "South Glamorgan", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SH", "", "", "Shropshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SK", "", "", "Suffolk", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SKS", "", "", "Selkirkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SL", "", "", "Shetland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SN", "", "", "Stockton-on-Tees", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SO", "", "", "Somerset", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SP", "", "", "Southampton", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SR", "", "", "Strabane", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SRK", "", "", "Sark", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SSX", "", "", "Sussex", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "ST", "", "", "Staffordshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "STI", "", "", "Stirlingshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SU", "", "", "Slough", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SUT", "", "", "Sutherland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SW", "", "", "West Sussex", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "SY", "", "", "Surrey", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "TA", "", "", "Tayside", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "TD", "", "", "Thamesdown", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "TH", "", "", "Thurrock", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "TO", "", "", "Torbay", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "TW", "", "", "Tyne and Wear", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "TYR", "", "", "Tyrone", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WA", "", "", "Warwickshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WD", "", "", "Windsor & Maidenhead", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WES", "", "", "Westmorland", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WG", "", "", "West Glamorgan", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WI", "", "", "Wiltshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WIG", "", "", "Wigtownshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WL", "", "", "Western Isles", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WLN", "", "", "West Lothian", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WM", "", "", "West Midlands", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WO", "", "", "Wokingham", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WOR", "", "", "Worcestershire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WR", "", "", "Wrekin", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WRY", "", "", "West Riding of Yorks", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "WT", "", "", "Warrington", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "YE", "", "", "East Yorkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "YK", "", "", "Yorkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "YN", "", "", "North Yorkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "YS", "", "", "South Yorkshire", "Vereinigtes Königreich", "United Kingdom"),
		array("500", "GB", "YW", "", "", "West Yorkshire", "Vereinigtes Königreich", "United Kingdom"),

		array("500", "HK", "99", "", "", "außerhalb", "Hong Kong", "Hong Kong"),
		array("500", "HK", "HK", "", "", " ", "Hong Kong", "Hong Kong"),
		array("500", "HK", "KLN", "", "", " ", "Hong Kong", "Hong Kong"),
		array("500", "HK", "NT", "", "", " ", "Hong Kong", "Hong Kong"),
		array("500", "HU", "1 ", "", "", "Allgemein", "Ungarn", "Hungary"),
		array("500", "HU", "99", "", "", "außerhalb", "Ungarn", "Hungary"),

		array("500", "ID", "01", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "02", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "03", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "04", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "05", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "06", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "07", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "08", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "09", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "10", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "11", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "12", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "13", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "14", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "15", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "16", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "17", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "18", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "19", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "20", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "21", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "22", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "23", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "24", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "25", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "26", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "27", "", "", " ", "Indonesien", "Indonesia"),
		array("500", "ID", "99", "", "", "außerhalb", "Indonesien", "Indonesia"),

		array("500", "IE", "99", "", "", "außerhalb", "Irland", "Ireland"),
		array("500", "IE", "CK", "", "", "Cork", "Irland", "Ireland"),
		array("500", "IE", "CL", "", "", "Clare", "Irland", "Ireland"),
		array("500", "IE", "CV", "", "", "Cavan", "Irland", "Ireland"),
		array("500", "IE", "CW", "", "", "Carlow", "Irland", "Ireland"),
		array("500", "IE", "DB", "", "", "Dublin", "Irland", "Ireland"),
		array("500", "IE", "DG", "", "", "Donegal", "Irland", "Ireland"),
		array("500", "IE", "GW", "", "", "Galway", "Irland", "Ireland"),
		array("500", "IE", "KD", "", "", "Kildare", "Irland", "Ireland"),
		array("500", "IE", "KK", "", "", "Kilkenny", "Irland", "Ireland"),
		array("500", "IE", "KY", "", "", "Kerry", "Irland", "Ireland"),
		array("500", "IE", "LF", "", "", "Longford", "Irland", "Ireland"),
		array("500", "IE", "LI", "", "", "Limerick", "Irland", "Ireland"),
		array("500", "IE", "LM", "", "", "Leitrim", "Irland", "Ireland"),
		array("500", "IE", "LS", "", "", "Laois", "Irland", "Ireland"),
		array("500", "IE", "LT", "", "", "Louth", "Irland", "Ireland"),
		array("500", "IE", "MH", "", "", "Monaghan", "Irland", "Ireland"),
		array("500", "IE", "MT", "", "", "Meath", "Irland", "Ireland"),
		array("500", "IE", "MY", "", "", "Mayo", "Irland", "Ireland"),
		array("500", "IE", "OF", "", "", "Offaly", "Irland", "Ireland"),
		array("500", "IE", "RC", "", "", "Roscommon", "Irland", "Ireland"),
		array("500", "IE", "SG", "", "", "Sligo", "Irland", "Ireland"),
		array("500", "IE", "TP", "", "", "Tipperary", "Irland", "Ireland"),
		array("500", "IE", "WF", "", "", "Waterford", "Irland", "Ireland"),
		array("500", "IE", "WK", "", "", "Wicklow", "Irland", "Ireland"),
		array("500", "IE", "WM", "", "", "Westmeath", "Irland", "Ireland"),
		array("500", "IE", "WX", "", "", "Wexford", "Irland", "Ireland"),

		array("500", "IN", "01", "", "", "Andra Pradesh", "Indien", "India"),
		array("500", "IN", "02", "", "", "Arunachal Pradesh", "Indien", "India"),
		array("500", "IN", "03", "", "", "Assam", "Indien", "India"),
		array("500", "IN", "04", "", "", "Bihar", "Indien", "India"),
		array("500", "IN", "05", "", "", "Goa", "Indien", "India"),
		array("500", "IN", "06", "", "", "Gujarat", "Indien", "India"),
		array("500", "IN", "07", "", "", "Haryana", "Indien", "India"),
		array("500", "IN", "08", "", "", "Himachal Pradesh", "Indien", "India"),
		array("500", "IN", "09", "", "", "Jammu and Kashmir", "Indien", "India"),
		array("500", "IN", "10", "", "", "Karnataka", "Indien", "India"),
		array("500", "IN", "11", "", "", "Kerala", "Indien", "India"),
		array("500", "IN", "12", "", "", "Madhya Pradesh", "Indien", "India"),
		array("500", "IN", "13", "", "", "Maharashtra", "Indien", "India"),
		array("500", "IN", "14", "", "", "Manipur", "Indien", "India"),
		array("500", "IN", "15", "", "", "Megalaya", "Indien", "India"),
		array("500", "IN", "16", "", "", "Mizoram", "Indien", "India"),
		array("500", "IN", "17", "", "", "Nagaland", "Indien", "India"),
		array("500", "IN", "18", "", "", "Orissa", "Indien", "India"),
		array("500", "IN", "19", "", "", "Punjab", "Indien", "India"),
		array("500", "IN", "20", "", "", "Rajasthan", "Indien", "India"),
		array("500", "IN", "21", "", "", "Sikkim", "Indien", "India"),
		array("500", "IN", "22", "", "", "Tamil Nadu", "Indien", "India"),
		array("500", "IN", "23", "", "", "Tripura", "Indien", "India"),
		array("500", "IN", "24", "", "", "Uttar Pradesh", "Indien", "India"),
		array("500", "IN", "25", "", "", "West Bengal", "Indien", "India"),
		array("500", "IN", "26", "", "", "Andaman and Nico.In.", "Indien", "India"),
		array("500", "IN", "27", "", "", "Chandigarh", "Indien", "India"),
		array("500", "IN", "28", "", "", "Dadra and Nagar Hav.", "Indien", "India"),
		array("500", "IN", "29", "", "", "Daman and Diu", "Indien", "India"),
		array("500", "IN", "30", "", "", "Delhi", "Indien", "India"),
		array("500", "IN", "31", "", "", "Lakshadweep", "Indien", "India"),
		array("500", "IN", "32", "", "", "Pondicherry", "Indien", "India"),
		array("500", "IN", "33", "", "", "Chhaattisgarh", "Indien", "India"),
		array("500", "IN", "34", "", "", "Jharkhand", "Indien", "India"),
		array("500", "IN", "35", "", "", "Uttaranchal", "Indien", "India"),

		array("500", "IT", "99", "", "", "außerhalb", "Italien", "Italy"),
		array("500", "IT", "AG", "", "", "Agrigento", "Italien", "Italy"),
		array("500", "IT", "AL", "", "", "Alessandria", "Italien", "Italy"),
		array("500", "IT", "AN", "", "", "Ancona", "Italien", "Italy"),
		array("500", "IT", "AO", "", "", "Aosta", "Italien", "Italy"),
		array("500", "IT", "AP", "", "", "Ascoli Piceno", "Italien", "Italy"),
		array("500", "IT", "AQ", "", "", "L'Aquila", "Italien", "Italy"),
		array("500", "IT", "AR", "", "", "Arezzo", "Italien", "Italy"),
		array("500", "IT", "AT", "", "", "Asti", "Italien", "Italy"),
		array("500", "IT", "AV", "", "", "Avellino", "Italien", "Italy"),
		array("500", "IT", "BA", "", "", "Bari", "Italien", "Italy"),
		array("500", "IT", "BG", "", "", "Bergamo", "Italien", "Italy"),
		array("500", "IT", "BI", "", "", "Biella", "Italien", "Italy"),
		array("500", "IT", "BL", "", "", "Belluno", "Italien", "Italy"),
		array("500", "IT", "BN", "", "", "Benevento", "Italien", "Italy"),
		array("500", "IT", "BO", "", "", "Bologna", "Italien", "Italy"),
		array("500", "IT", "BR", "", "", "Brindisi", "Italien", "Italy"),
		array("500", "IT", "BS", "", "", "Brescia", "Italien", "Italy"),
		array("500", "IT", "BZ", "", "", "Bolzano", "Italien", "Italy"),
		array("500", "IT", "CA", "", "", "Cagliari", "Italien", "Italy"),
		array("500", "IT", "CB", "", "", "Campobasso", "Italien", "Italy"),
		array("500", "IT", "CE", "", "", "Caserta", "Italien", "Italy"),
		array("500", "IT", "CH", "", "", "Chieti", "Italien", "Italy"),
		array("500", "IT", "CL", "", "", "Caltanisetta", "Italien", "Italy"),
		array("500", "IT", "CN", "", "", "Cuneo", "Italien", "Italy"),
		array("500", "IT", "CO", "", "", "Como", "Italien", "Italy"),
		array("500", "IT", "CR", "", "", "Cremona", "Italien", "Italy"),
		array("500", "IT", "CS", "", "", "Cosenza", "Italien", "Italy"),
		array("500", "IT", "CT", "", "", "Catania", "Italien", "Italy"),
		array("500", "IT", "CZ", "", "", "Catanzaro", "Italien", "Italy"),
		array("500", "IT", "EN", "", "", "Enna", "Italien", "Italy"),
		array("500", "IT", "FC", "", "", "Forlì Cesena", "Italien", "Italy"),
		array("500", "IT", "FE", "", "", "Ferrara", "Italien", "Italy"),
		array("500", "IT", "FG", "", "", "Foggia", "Italien", "Italy"),
		array("500", "IT", "FI", "", "", "Firenze", "Italien", "Italy"),
		array("500", "IT", "FO", "", "", "Forlì", "Italien", "Italy"),
		array("500", "IT", "FR", "", "", "Frosinone", "Italien", "Italy"),
		array("500", "IT", "GE", "", "", "Genova", "Italien", "Italy"),
		array("500", "IT", "GO", "", "", "Gorizia", "Italien", "Italy"),
		array("500", "IT", "GR", "", "", "Grosseto", "Italien", "Italy"),
		array("500", "IT", "IM", "", "", "Imperia", "Italien", "Italy"),
		array("500", "IT", "IS", "", "", "Isernia", "Italien", "Italy"),
		array("500", "IT", "KR", "", "", "Crotone", "Italien", "Italy"),
		array("500", "IT", "LC", "", "", "Lecco", "Italien", "Italy"),
		array("500", "IT", "LE", "", "", "Lecce", "Italien", "Italy"),
		array("500", "IT", "LI", "", "", "Livorno", "Italien", "Italy"),
		array("500", "IT", "LO", "", "", "Lodi", "Italien", "Italy"),
		array("500", "IT", "LT", "", "", "Latina", "Italien", "Italy"),
		array("500", "IT", "LU", "", "", "Lucca", "Italien", "Italy"),
		array("500", "IT", "MB", "", "", "Monza/Brianza", "Italien", "Italy"),
		array("500", "IT", "MC", "", "", "Macerata", "Italien", "Italy"),
		array("500", "IT", "ME", "", "", "Messina", "Italien", "Italy"),
		array("500", "IT", "MI", "", "", "Milano", "Italien", "Italy"),
		array("500", "IT", "MN", "", "", "Mantova", "Italien", "Italy"),
		array("500", "IT", "MO", "", "", "Modena", "Italien", "Italy"),
		array("500", "IT", "MS", "", "", "Massa Carrara", "Italien", "Italy"),
		array("500", "IT", "MT", "", "", "Matera", "Italien", "Italy"),
		array("500", "IT", "NA", "", "", "Napoli", "Italien", "Italy"),
		array("500", "IT", "NO", "", "", "Novara", "Italien", "Italy"),
		array("500", "IT", "NU", "", "", "Nuoro", "Italien", "Italy"),
		array("500", "IT", "OR", "", "", "Oristano", "Italien", "Italy"),
		array("500", "IT", "PA", "", "", "Palermo", "Italien", "Italy"),
		array("500", "IT", "PC", "", "", "Piacenza", "Italien", "Italy"),
		array("500", "IT", "PD", "", "", "Padova", "Italien", "Italy"),
		array("500", "IT", "PE", "", "", "Pescara", "Italien", "Italy"),
		array("500", "IT", "PG", "", "", "Perugia", "Italien", "Italy"),
		array("500", "IT", "PI", "", "", "Pisa", "Italien", "Italy"),
		array("500", "IT", "PN", "", "", "Pordenone", "Italien", "Italy"),
		array("500", "IT", "PO", "", "", "Prato", "Italien", "Italy"),
		array("500", "IT", "PR", "", "", "Parma", "Italien", "Italy"),
		array("500", "IT", "PS", "", "", "Pesaro", "Italien", "Italy"),
		array("500", "IT", "PT", "", "", "Pistoia", "Italien", "Italy"),
		array("500", "IT", "PU", "", "", "Pesaro-Urbino", "Italien", "Italy"),
		array("500", "IT", "PV", "", "", "Pavia", "Italien", "Italy"),
		array("500", "IT", "PZ", "", "", "Potenza", "Italien", "Italy"),
		array("500", "IT", "RA", "", "", "Ravenna", "Italien", "Italy"),
		array("500", "IT", "RC", "", "", "Reggio Calabria", "Italien", "Italy"),
		array("500", "IT", "RE", "", "", "Reggio Emilia", "Italien", "Italy"),
		array("500", "IT", "RG", "", "", "Ragusa", "Italien", "Italy"),
		array("500", "IT", "RI", "", "", "Rieti", "Italien", "Italy"),
		array("500", "IT", "RM", "", "", "Roma", "Italien", "Italy"),
		array("500", "IT", "RN", "", "", "Rimini", "Italien", "Italy"),
		array("500", "IT", "RO", "", "", "Rovigo", "Italien", "Italy"),
		array("500", "IT", "RV", "029", "", "Ravenna", "Italien", "Italy"),
		array("500", "IT", "SA", "", "", "Salerno", "Italien", "Italy"),
		array("500", "IT", "SI", "", "", "Siena", "Italien", "Italy"),
		array("500", "IT", "SO", "", "", "Sondrio", "Italien", "Italy"),
		array("500", "IT", "SP", "", "", "La Spezia", "Italien", "Italy"),
		array("500", "IT", "SR", "", "", "Siracusa", "Italien", "Italy"),
		array("500", "IT", "SS", "", "", "Sassari", "Italien", "Italy"),
		array("500", "IT", "SV", "", "", "Savona", "Italien", "Italy"),
		array("500", "IT", "TA", "", "", "Taranto", "Italien", "Italy"),
		array("500", "IT", "TE", "", "", "Teramo", "Italien", "Italy"),
		array("500", "IT", "TN", "", "", "Trento", "Italien", "Italy"),
		array("500", "IT", "TO", "", "", "Torino", "Italien", "Italy"),
		array("500", "IT", "TP", "", "", "Trapani", "Italien", "Italy"),
		array("500", "IT", "TR", "", "", "Terni", "Italien", "Italy"),
		array("500", "IT", "TS", "", "", "Trieste", "Italien", "Italy"),
		array("500", "IT", "TV", "", "", "Treviso", "Italien", "Italy"),
		array("500", "IT", "UD", "", "", "Udine", "Italien", "Italy"),
		array("500", "IT", "VA", "", "", "Varese", "Italien", "Italy"),
		array("500", "IT", "VB", "", "", "Verbano-Cusio-Ossola", "Italien", "Italy"),
		array("500", "IT", "VC", "", "", "Vercelli", "Italien", "Italy"),
		array("500", "IT", "VE", "", "", "Venezia", "Italien", "Italy"),
		array("500", "IT", "VI", "", "", "Vicenza", "Italien", "Italy"),
		array("500", "IT", "VR", "", "", "Verona", "Italien", "Italy"),
		array("500", "IT", "VT", "", "", "Viterbo", "Italien", "Italy"),
		array("500", "IT", "VV", "", "", "Vibo Valentia", "Italien", "Italy"),

		array("500", "JP", "01", "", "", "Hokkaido", "Japan", "Japan"),
		array("500", "JP", "02", "", "", "Aomori-ken", "Japan", "Japan"),
		array("500", "JP", "03", "", "", "Iwate-ken", "Japan", "Japan"),
		array("500", "JP", "04", "", "", "Miyagi-ken", "Japan", "Japan"),
		array("500", "JP", "05", "", "", "Akita-ken", "Japan", "Japan"),
		array("500", "JP", "06", "", "", "Yamagata-ken", "Japan", "Japan"),
		array("500", "JP", "07", "", "", "Fukushima-ken", "Japan", "Japan"),
		array("500", "JP", "08", "", "", "Ibaragi-ken", "Japan", "Japan"),
		array("500", "JP", "09", "", "", "Tochigi-ken", "Japan", "Japan"),
		array("500", "JP", "10", "", "", "Gunma-ken", "Japan", "Japan"),
		array("500", "JP", "11", "", "", "Saitama-ken", "Japan", "Japan"),
		array("500", "JP", "12", "", "", "Chiba-ken", "Japan", "Japan"),
		array("500", "JP", "13", "", "", "Tokyo-to", "Japan", "Japan"),
		array("500", "JP", "14", "", "", "Kanagawa-ken", "Japan", "Japan"),
		array("500", "JP", "15", "", "", "Niigata-ken", "Japan", "Japan"),
		array("500", "JP", "16", "", "", "Toyama-ken", "Japan", "Japan"),
		array("500", "JP", "17", "", "", "Ishikawa-ken", "Japan", "Japan"),
		array("500", "JP", "18", "", "", "Fukui-ken", "Japan", "Japan"),
		array("500", "JP", "19", "", "", "Yamanashi-ken", "Japan", "Japan"),
		array("500", "JP", "20", "", "", "Nagano-ken", "Japan", "Japan"),
		array("500", "JP", "21", "", "", "Gifu-ken", "Japan", "Japan"),
		array("500", "JP", "22", "", "", "Shizuoka-ken", "Japan", "Japan"),
		array("500", "JP", "23", "", "", "Aichi-ken", "Japan", "Japan"),
		array("500", "JP", "24", "", "", "Mie-ken", "Japan", "Japan"),
		array("500", "JP", "25", "", "", "Shiga-ken", "Japan", "Japan"),
		array("500", "JP", "26", "", "", "Kyoto-fu", "Japan", "Japan"),
		array("500", "JP", "27", "", "", "Osaka-fu", "Japan", "Japan"),
		array("500", "JP", "28", "", "", "Hyogo-ken", "Japan", "Japan"),
		array("500", "JP", "29", "", "", "Nara-ken", "Japan", "Japan"),
		array("500", "JP", "30", "", "", "Wakayama-ken", "Japan", "Japan"),
		array("500", "JP", "31", "", "", "Tottori-ken", "Japan", "Japan"),
		array("500", "JP", "32", "", "", "Shimane-ken", "Japan", "Japan"),
		array("500", "JP", "33", "", "", "Okayama-ken", "Japan", "Japan"),
		array("500", "JP", "34", "", "", "Hiroshima-ken", "Japan", "Japan"),
		array("500", "JP", "35", "", "", "Yamaguchi-ken", "Japan", "Japan"),
		array("500", "JP", "36", "", "", "Tokushima-ken", "Japan", "Japan"),
		array("500", "JP", "37", "", "", "Kagawa-ken", "Japan", "Japan"),
		array("500", "JP", "38", "", "", "Ehime-ken", "Japan", "Japan"),
		array("500", "JP", "39", "", "", "Kochi-ken", "Japan", "Japan"),
		array("500", "JP", "40", "", "", "Fukuoka-ken", "Japan", "Japan"),
		array("500", "JP", "41", "", "", "Saga-ken", "Japan", "Japan"),
		array("500", "JP", "42", "", "", "Nagasaki-ken", "Japan", "Japan"),
		array("500", "JP", "43", "", "", "Kumamoto-ken", "Japan", "Japan"),
		array("500", "JP", "44", "", "", "Oita-ken", "Japan", "Japan"),
		array("500", "JP", "45", "", "", "Miyazaki-ken", "Japan", "Japan"),
		array("500", "JP", "46", "", "", "Kagoshima-ken", "Japan", "Japan"),
		array("500", "JP", "47", "", "", "Okinawa-ken", "Japan", "Japan"),
		array("500", "JP", "99", "", "", "außerhalb", "Japan", "Japan"),

		array("500", "KR", "01", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "02", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "03", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "04", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "05", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "06", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "07", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "08", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "09", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "10", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "11", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "12", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "13", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "14", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "15", "", "", " ", "Korea, Rep.", "Korea, Republic of"),
		array("500", "KR", "99", "", "", "außerhalb", "Korea, Rep.", "Korea, Republic of"),

		array("500", "MC", "99", "", "", "außerhalb", "Monaco", "Monaco"),

		array("500", "MX", "99", "", "", "außerhalb", "Mexiko", "Mexico"),
		array("500", "MX", "AGS", "", "", "Aguascalientes", "Mexiko", "Mexico"),
		array("500", "MX", "BC", "", "", "Baja California", "Mexiko", "Mexico"),
		array("500", "MX", "BCS", "", "", "Baja California S", "Mexiko", "Mexico"),
		array("500", "MX", "CHI", "", "", "Chihuahua", "Mexiko", "Mexico"),
		array("500", "MX", "CHS", "", "", "Chiapas", "Mexiko", "Mexico"),
		array("500", "MX", "CMP", "", "", "Campeche", "Mexiko", "Mexico"),
		array("500", "MX", "COA", "", "", "Coahuila", "Mexiko", "Mexico"),
		array("500", "MX", "COL", "", "", "Colima", "Mexiko", "Mexico"),
		array("500", "MX", "DF", "", "", "Distrito Federal", "Mexiko", "Mexico"),
		array("500", "MX", "DGO", "", "", "Durango", "Mexiko", "Mexico"),
		array("500", "MX", "GRO", "", "", "Guerrero", "Mexiko", "Mexico"),
		array("500", "MX", "GTO", "", "", "Guanajuato", "Mexiko", "Mexico"),
		array("500", "MX", "HGO", "", "", "Hidalgo", "Mexiko", "Mexico"),
		array("500", "MX", "JAL", "", "", "Jalisco", "Mexiko", "Mexico"),
		array("500", "MX", "MCH", "", "", "Michoacán", "Mexiko", "Mexico"),
		array("500", "MX", "MEX", "", "", "Estado de México", "Mexiko", "Mexico"),
		array("500", "MX", "MOR", "", "", "Morelos", "Mexiko", "Mexico"),
		array("500", "MX", "NAY", "", "", "Nayarit", "Mexiko", "Mexico"),
		array("500", "MX", "NL", "", "", "Nuevo León", "Mexiko", "Mexico"),
		array("500", "MX", "OAX", "", "", "Oaxaca", "Mexiko", "Mexico"),
		array("500", "MX", "PUE", "", "", "Puebla", "Mexiko", "Mexico"),
		array("500", "MX", "QR", "", "", "Quintana Roo", "Mexiko", "Mexico"),
		array("500", "MX", "QRO", "", "", "Querétaro", "Mexiko", "Mexico"),
		array("500", "MX", "SIN", "", "", "Sinaloa", "Mexiko", "Mexico"),
		array("500", "MX", "SLP", "", "", "San Luis Potosí", "Mexiko", "Mexico"),
		array("500", "MX", "SON", "", "", "Sonora", "Mexiko", "Mexico"),
		array("500", "MX", "TAB", "", "", "Tabasco", "Mexiko", "Mexico"),
		array("500", "MX", "TLX", "", "", "Tlaxcala", "Mexiko", "Mexico"),
		array("500", "MX", "TMS", "", "", "Tamaulipas", "Mexiko", "Mexico"),
		array("500", "MX", "VER", "", "", "Veracruz", "Mexiko", "Mexico"),
		array("500", "MX", "YUC", "", "", "Yucatán", "Mexiko", "Mexico"),
		array("500", "MX", "ZAC", "", "", "Zacatecas", "Mexiko", "Mexico"),

		array("500", "MY", "99", "", "", "außerhalb", "Malaysia", "Malaysia"),
		array("500", "MY", "JOH", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "KED", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "KEL", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "KUL", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "LAB", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "MEL", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "PAH", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "PEL", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "PER", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "PIN", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "SAB", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "SAR", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "SEL", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "SER", "", "", " ", "Malaysia", "Malaysia"),
		array("500", "MY", "TRE", "", "", " ", "Malaysia", "Malaysia"),

		array("500", "NB", "08", "", "", "EDI", "", ""),
		array("500", "NL", "", "001", "", " ", "Niederlande", "Netherlands"),
		array("500", "NL", "99", "", "", "außerhalb", "Niederlande", "Netherlands"),

		array("500", "NO", "01", "", "", "Østfold Fylke", "Norwegen", "Norway"),
		array("500", "NO", "02", "", "", "Akershus Fylke", "Norwegen", "Norway"),
		array("500", "NO", "03", "", "", "Oslo", "Norwegen", "Norway"),
		array("500", "NO", "04", "", "", "Hedmark Fylke", "Norwegen", "Norway"),
		array("500", "NO", "05", "", "", "Oppland Fylke", "Norwegen", "Norway"),
		array("500", "NO", "06", "", "", "Buskerud Fylke", "Norwegen", "Norway"),
		array("500", "NO", "07", "", "", "Vestfold Fylke", "Norwegen", "Norway"),
		array("500", "NO", "08", "", "", "Telemark Fylke", "Norwegen", "Norway"),
		array("500", "NO", "09", "", "", "Aust-Agder Fylke", "Norwegen", "Norway"),
		array("500", "NO", "10", "", "", "Vest-Agder Fylke", "Norwegen", "Norway"),
		array("500", "NO", "11", "", "", "Rogaland Fylke", "Norwegen", "Norway"),
		array("500", "NO", "12", "", "", "Hordaland Fylke", "Norwegen", "Norway"),
		array("500", "NO", "14", "", "", "Sogn og Fjordane F.", "Norwegen", "Norway"),
		array("500", "NO", "15", "", "", "Møre og Romsdal F.", "Norwegen", "Norway"),
		array("500", "NO", "16", "", "", "Sør-Trøndelag Fylke", "Norwegen", "Norway"),
		array("500", "NO", "17", "", "", "Nord-Trøndelag Fylke", "Norwegen", "Norway"),
		array("500", "NO", "18", "", "", "Nordland Fylke", "Norwegen", "Norway"),
		array("500", "NO", "19", "", "", "Troms Fylke", "Norwegen", "Norway"),
		array("500", "NO", "20", "", "", "Finnmark Fylke", "Norwegen", "Norway"),
		array("500", "NO", "21", "", "", "Svalbard", "Norwegen", "Norway"),
		array("500", "NO", "99", "", "", "außerhalb", "Norwegen", "Norway"),


		array("500", "NZ", "99", "", "", "außerhalb", "Neuseeland", "New Zealand"),
		array("500", "NZ", "AKL", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "BOI", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "BOP", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "CAN", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "CHC", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "DUN", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "EAC", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "FIO", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "HAB", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "KNG", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "MAN", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "MIC", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "MRL", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "MRT", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "NLS", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "NOC", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "NTL", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "OTA", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "SOC", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "STL", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "TAR", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "WAI", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "WAR", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "WLG", "", "", " ", "Neuseeland", "New Zealand"),
		array("500", "NZ", "WTL", "", "", " ", "Neuseeland", "New Zealand"),

		array("500", "PL", "99", "", "", "nn", "Polen", "Poland"),

		array("500", "PT", "10", "", "", "Minho-Lima", "Portugal", "Portugal"),
		array("500", "PT", "11", "", "", "Cávado", "Portugal", "Portugal"),
		array("500", "PT", "12", "", "", "Ave", "Portugal", "Portugal"),
		array("500", "PT", "13", "", "", "Grande Porto", "Portugal", "Portugal"),
		array("500", "PT", "14", "", "", "Tâmega", "Portugal", "Portugal"),
		array("500", "PT", "15", "", "", "Entre Douro e Vouga", "Portugal", "Portugal"),
		array("500", "PT", "16", "", "", "Douro", "Portugal", "Portugal"),
		array("500", "PT", "17", "", "", "Alto Trás-os-Montes", "Portugal", "Portugal"),
		array("500", "PT", "20", "", "", "Baixo Vouga", "Portugal", "Portugal"),
		array("500", "PT", "21", "", "", "Baixo Mondego", "Portugal", "Portugal"),
		array("500", "PT", "22", "", "", "Pinhal Litoral", "Portugal", "Portugal"),
		array("500", "PT", "23", "", "", "Pinhal Interior N.", "Portugal", "Portugal"),
		array("500", "PT", "24", "", "", "Pinhal Interior Sul", "Portugal", "Portugal"),
		array("500", "PT", "25", "", "", "Dão-Lafoes", "Portugal", "Portugal"),
		array("500", "PT", "26", "", "", "Serra da Estrela", "Portugal", "Portugal"),
		array("500", "PT", "27", "", "", "Beira Interior Norte", "Portugal", "Portugal"),
		array("500", "PT", "28", "", "", "Beira Interior Sul", "Portugal", "Portugal"),
		array("500", "PT", "29", "", "", "Cova da Beira", "Portugal", "Portugal"),
		array("500", "PT", "30", "", "", "Oeste", "Portugal", "Portugal"),
		array("500", "PT", "31", "", "", "Grande Lisboa", "Portugal", "Portugal"),
		array("500", "PT", "32", "", "", "Península de Setúbal", "Portugal", "Portugal"),
		array("500", "PT", "33", "", "", "Médio Tejo", "Portugal", "Portugal"),
		array("500", "PT", "34", "", "", "Lezíria do Tejo", "Portugal", "Portugal"),
		array("500", "PT", "40", "", "", "Alentejo Litoral", "Portugal", "Portugal"),
		array("500", "PT", "41", "", "", "Alto Alentejo", "Portugal", "Portugal"),
		array("500", "PT", "42", "", "", "Alentejo Central", "Portugal", "Portugal"),
		array("500", "PT", "43", "", "", "Baixo Alentejo", "Portugal", "Portugal"),
		array("500", "PT", "50", "", "", "Algarve", "Portugal", "Portugal"),
		array("500", "PT", "60", "", "", "Reg. Aut. dos Açores", "Portugal", "Portugal"),
		array("500", "PT", "70", "", "", "Reg. Aut. da Madeira", "Portugal", "Portugal"),
		array("500", "PT", "99", "", "", "außerhalb", "Portugal", "Portugal"),

		array("500", "RO", "99", "", "", "Rumänien", "Rumänien", "Romania"),

		array("500", "RU", "99", "", "", "Russland", "Russische Föderation", "Russian Federation"),

		array("500", "SE", "001", "", "", "Älvsborgs Län", "Schweden", "Sweden"),
		array("500", "SE", "002", "", "", "Blekinge Län", "Schweden", "Sweden"),
		array("500", "SE", "003", "", "", "Gävleborg Län", "Schweden", "Sweden"),
		array("500", "SE", "004", "", "", "Göteborg och Bohus", "Schweden", "Sweden"),
		array("500", "SE", "005", "", "", "Gotlands Län", "Schweden", "Sweden"),
		array("500", "SE", "006", "", "", "Hallands Län", "Schweden", "Sweden"),
		array("500", "SE", "007", "", "", "Jämtlands Län", "Schweden", "Sweden"),
		array("500", "SE", "008", "", "", "Jönköpings Län", "Schweden", "Sweden"),
		array("500", "SE", "009", "", "", "Kalmar Län", "Schweden", "Sweden"),
		array("500", "SE", "010", "", "", "Kopparbergs Län", "Schweden", "Sweden"),
		array("500", "SE", "011", "", "", "Kristianstads Län", "Schweden", "Sweden"),
		array("500", "SE", "012", "", "", "Kronobergs Län", "Schweden", "Sweden"),
		array("500", "SE", "013", "", "", "Malmöhus Län", "Schweden", "Sweden"),
		array("500", "SE", "014", "", "", "Norrbottens Län", "Schweden", "Sweden"),
		array("500", "SE", "015", "", "", "Örebro Län", "Schweden", "Sweden"),
		array("500", "SE", "016", "", "", "Östergötlands Län", "Schweden", "Sweden"),
		array("500", "SE", "017", "", "", "Skaraborgs Län", "Schweden", "Sweden"),
		array("500", "SE", "018", "", "", "Södermanlands Län", "Schweden", "Sweden"),
		array("500", "SE", "019", "", "", "Stockholm Län", "Schweden", "Sweden"),
		array("500", "SE", "020", "", "", "Uppsala Län", "Schweden", "Sweden"),
		array("500", "SE", "021", "", "", "Värmlands Län", "Schweden", "Sweden"),
		array("500", "SE", "022", "", "", "Västerbottens Län", "Schweden", "Sweden"),
		array("500", "SE", "023", "", "", "Västernorrlands Län", "Schweden", "Sweden"),
		array("500", "SE", "024", "", "", "Västmanlands Län", "Schweden", "Sweden"),
		array("500", "SE", "99", "", "", "außerhalb", "Schweden", "Sweden"),


		array("500", "SG", "99", "", "", "außerhalb", "Singapur", "Singapore"),
		array("500", "SG", "SE", "", "", " ", "Singapur", "Singapore"),
		array("500", "SG", "SN", "", "", " ", "Singapur", "Singapore"),
		array("500", "SG", "SS", "", "", " ", "Singapur", "Singapore"),
		array("500", "SG", "SW", "", "", " ", "Singapur", "Singapore"),

		array("500", "SI", "SI", "", "", "Slowenien", "Slowenien", "Slovenia"),
		array("500", "SK", "99", "", "", "außerhalb", "Slowakei", "Slovakia (Slovak Republic)"),

		array("500", "TH", "99", "", "", "außerhalb", "Thailand", "Thailand"),
		array("500", "TH", "C ", "", "", " ", "Thailand", "Thailand"),
		array("500", "TH", "E ", "", "", " ", "Thailand", "Thailand"),
		array("500", "TH", "N ", "", "", " ", "Thailand", "Thailand"),
		array("500", "TH", "S ", "", "", " ", "Thailand", "Thailand"),
		array("500", "TH", "W ", "", "", " ", "Thailand", "Thailand"),

		array("500", "TN", "AR", "", "", "Ariana", "Tunesien", "Tunisia"),
		array("500", "TN", "BA", "", "", "Ben Arous", "Tunesien", "Tunisia"),
		array("500", "TN", "BE", "", "", "Beja", "Tunesien", "Tunisia"),
		array("500", "TN", "BI", "", "", "Bizerte", "Tunesien", "Tunisia"),
		array("500", "TN", "GA", "", "", "Gafsa", "Tunesien", "Tunisia"),
		array("500", "TN", "GB", "", "", "Gabès", "Tunesien", "Tunisia"),
		array("500", "TN", "JE", "", "", "Jendouba", "Tunesien", "Tunisia"),
		array("500", "TN", "KA", "", "", "Kairouan", "Tunesien", "Tunisia"),
		array("500", "TN", "KE", "", "", "Kebili", "Tunesien", "Tunisia"),
		array("500", "TN", "KS", "", "", "Kasserine", "Tunesien", "Tunisia"),
		array("500", "TN", "MA", "", "", "Manouba", "Tunesien", "Tunisia"),
		array("500", "TN", "ME", "", "", "Medenine", "Tunesien", "Tunisia"),
		array("500", "TN", "MH", "", "", "Mahdia", "Tunesien", "Tunisia"),
		array("500", "TN", "MO", "", "", "Monastir", "Tunesien", "Tunisia"),
		array("500", "TN", "NA", "", "", "Nabeul", "Tunesien", "Tunisia"),
		array("500", "TN", "SB", "", "", "Sidi Bou Zid", "Tunesien", "Tunisia"),
		array("500", "TN", "SF", "", "", "Sfax", "Tunesien", "Tunisia"),
		array("500", "TN", "SI", "", "", "Siliana", "Tunesien", "Tunisia"),
		array("500", "TN", "SO", "", "", "Sousse", "Tunesien", "Tunisia"),
		array("500", "TN", "TA", "", "", "Tabarka, Le Kef", "Tunesien", "Tunisia"),
		array("500", "TN", "TO", "", "", "Tozeur", "Tunesien", "Tunisia"),
		array("500", "TN", "TT", "", "", "Tataouine", "Tunesien", "Tunisia"),
		array("500", "TN", "TU", "", "", "Tunis", "Tunesien", "Tunisia"),
		array("500", "TN", "ZA", "", "", "Zaghouan", "Tunesien", "Tunisia"),

		array("500", "TW", "99", "", "", "außerhalb", "Taiwan", "Taiwan, Province of China"),
		array("500", "TW", "FJN", "", "", " ", "Taiwan", "Taiwan, Province of China"),
		array("500", "TW", "KSH", "", "", " ", "Taiwan", "Taiwan, Province of China"),
		array("500", "TW", "TPE", "", "", " ", "Taiwan", "Taiwan, Province of China"),
		array("500", "TW", "TWN", "", "", " ", "Taiwan", "Taiwan, Province of China"),

		array("500", "US", "99", "", "", "außerhalb", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "AK", "", "", "Alaska", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "AL", "01", "", "Alabama", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "AR", "05", "", "Arkansas", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "AS", "", "", "American Samoa", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "AZ", "04", "", "Arizona", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "CA", "06", "", "California", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "CO", "", "", "Colorado", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "CT", "", "", "Connecticut", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "DC", "11", "", "District of Columbia", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "DE", "10", "", "Delaware", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "FL", "", "", "Florida", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "GA", "13", "", "Georgia", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "GU", "", "", "Guam", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "HI", "15", "", "Hawaii", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "IA", "19", "", "Iowa", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "ID", "16", "", "Idaho", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "IL", "", "", "Illinois", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "IN", "18", "", "Indiana", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "KS", "20", "", "Kansas", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "KY", "", "", "Kentucky", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "LA", "", "", "Louisiana", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MA", "25", "", "Massachusetts", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MD", "", "", "Maryland", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "ME", "23", "", "Maine", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MI", "", "", "Michigan", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MN", "27", "", "Minnesota", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MO", "29", "", "Missouri", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MP", "", "", "Northern Mariana Isl", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MS", "28", "", "Mississippi", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "MT", "30", "", "Montana", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NC", "37", "", "North Carolina", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "ND", "38", "", "North Dakota", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NE", "", "", "Nebraska", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NH", "", "", "New Hampshire", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NJ", "34", "", "New Jersey", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NM", "35", "", "New Mexico", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NV", "", "", "Nevada", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "NY", "36", "", "New York", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "OH", "", "", "Ohio", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "OK", "", "", "Oklahoma", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "OR", "41", "", "Oregon", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "PA", "", "", "Pennsylvania", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "PR", "", "", "Puerto Rico", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "RI", "40", "", "Rhode Island", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "SC", "45", "", "South Carolina", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "SD", "", "", "South Dakota", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "TN", "47", "", "Tennessee", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "TX", "", "", "Texas", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "UT", "", "", "Utah", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "VA", "", "", "Virginia", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "VI", "", "", "Virgin Islands", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "VT", "", "", "Vermont", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "WA", "", "", "Washington", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "WI", "55", "", "Wisconsin", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "WV", "", "", "West Virginia", "Vereinigte Staaten von Amerika", "United States"),
		array("500", "US", "WY", "", "", "Wyoming", "Vereinigte Staaten von Amerika", "United States"),

		array("500", "ZA", "99", "", "", "außerhalb", "Südafrika", "South Africa"),
		array("500", "ZA", "EC", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "FS", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "GA", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "KW", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "MM", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "NA", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "NC", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "NP", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "NW", "", "", " ", "Südafrika", "South Africa"),
		array("500", "ZA", "WC", "", "", " ", "Südafrika", "South Africa"),
	);

	return $arRegions;
}